app = "appname"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
image = "vaultwarden/server:latest"

[env]
SIGNUPS_ALLOWED=true # disable after initial setup
INVITATIONS_ALLOWED=true
SHOW_PASSWORD_HINT=false
# WEBSOCKET_ENABLED=true # Required to use websockets
# DOMAIN='https://[DOMAIN]'
# ADMIN_TOKEN='some-super-admin-token'
SMTP_HOST='smtp.gmail.com'
SMTP_PORT=587
SMTP_SECURITY='starttls'
SMTP_USERNAME='mail@gmail.com'
SMTP_PASSWORD='superpass'
YUBICO_CLIENT_ID='[OPTIONAL]'
YUBICO_SECRET_KEY='[OPTIONAL]'

[mounts]
source="vaultwarden_data"
destination="/data"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 80
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
